NO_PERROR: control overriding of perror() symbol
Doing static builds of portmap might fail when the C library's perror()
function is pulled in and collides with portmap's definition.  So add a
flag to control the local override.

Signed-off-by: Mike Frysinger <vapier@gentoo.org>
Signed-off-by: Neil Brown <neilb@suse.de>